#!/bin/sh
# This file is for cron job

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin

# This if for make sure the start cgminer when there is network problem
C=`pidof cgminer | wc -l`
if [ "$C" != "1" ]; then
    killall -s 9 cgminer
    sleep 2
    /etc/init.d/cgminer start
    exit 0;
fi

B=`cgminer-api devs | grep "^   \[Last Valid Work\]" | grep -o "[0-9]\+"`
if [ "$?" != "0" ]; then
    killall -s 9 cgminer
    sleep 2
    /etc/init.d/cgminer start
    exit 0;
fi

A=`cat /tmp/cm.log`
echo -n "$B" > /tmp/cm.log
if [ "$A" -eq "$B" ]; then
    killall -s 9 cgminer
    sleep 2
    /etc/init.d/cgminer start
    exit 0;
fi
